### ISSUE TITLE
Can you do this for AIDA64 as well?

### ISSUE THREAD

**Issue by FieryUP** [shayne/hwinfo-streamdeck#11]
AIDA64 also supports shared memory, so forking this project to suit AIDA64 should be relatively easy.  Let me know if you're interested.  If not, let me know (in email) whether you would allow us to build our own Stream Deck plugin based on yours.

Best Regards,
Tamas Miklos (a.k.a. Fiery)

tamas.miklos@finalwire.com
FinalWire Ltd.
www.aida64.com

**Comment by shayne** [comment]
Reached out via email

**Comment by robertoleonardo** [comment]
i take it this isn't happening?  the "support" for streamdeck built in to aida64 is not, in fact, real support.  i'm trying to transition to aida64 extreme from hwinfo but this is killing me.  come on @FieryUP :)!
