### ISSUE TITLE
[Feature Request] Multiple lines - Format: \n

### ISSUE THREAD

**Issue by Jonn3y** [shayne/hwinfo-streamdeck#15]
Hey,

is it possible to add support for `\n` in Format ?

Would love to show the unit (MB, KB, %, ...) i a second row.
![image](https://user-images.githubusercontent.com/11927089/76516459-c188f000-645b-11ea-9525-305a55f418ff.png)

`\n` does not work:
![image](https://user-images.githubusercontent.com/11927089/76516565-e8dfbd00-645b-11ea-9776-ffb82f183353.png)

Greetings!

**Comment by thebonden** [comment]
hi how did you get it to convert the numbers to MB / s when I key it in you have made my numbers do not match with MB / s when I do a speed test 104 MB / s on the website but on the meter I get
some completely wild numbers

**Comment by shayne** [comment]
Added support for this in:
https://github.com/shayne/hwinfo-streamdeck/releases/tag/v1.1.4
