### ISSUE TITLE
Range for temperature values

### ISSUE THREAD

**Issue by pjw29** [shayne/hwinfo-streamdeck#16]
When i set a small range for some termperature value, say 40 degrees to 90 degrees, the tile doesn't scale correctly and it looks more like its 40 - 140 degrees. If I run the scale from 0 - 100, its fine.

**Comment by kevind003** [comment]
same for me I am running at 42C - I want to keep it in C so I don't mess up my concept of F
but I want to set it to say, 37C at the low end (prol thinking of fareinheit though as a scale duh)
and then uhm well its actually 47C at the high end, and have 191 levels between the two

so the graph would draw from 37 to 47, with 191 levels (user assignable for fluid graphics)
and then the update at like 235-250ms user assignable (plus what the other guy said about the timing)

sound good? seems someone else has this issue

**Comment by kevind003** [comment]
oops I meant to write that mine doesn't work, its set to 37-47C and it shows 42 at the bottom like, a couple of lines

**Comment by dayjobtitus** [comment]
I have this same issue but it only recently started so I assume it has to do with updates to HWINFO but unsure.

**Comment by shayne** [comment]
You're right, it's a bug. Looking into a fix.

**Comment by shayne** [comment]
https://github.com/shayne/hwinfo-streamdeck/releases/tag/v1.1.3

Check out this release and report back if you still find an issue.
