### ISSUE TITLE
HwInfo Strem Deck

### ISSUE THREAD

**Issue by MaverikMS2001** [shayne/hwinfo-streamdeck#17]
How can i Dsiplay the GPU Temp. It's not availiable in the dropdown but i can see it in hwinfo.

**Comment by shayne** [comment]
Check the Sensor selected in the Stream Deck app and compare it to the section title in HWiNFO.  It should be one of your GPU sensors.

![image](https://user-images.githubusercontent.com/79330/87993181-b9daf700-ca9e-11ea-9c67-a80ff4c8929a.png)
