### ISSUE TITLE
cant change font colors/size for title

### ISSUE THREAD

**Issue by diplomaticENTERTAINMENT** [shayne/hwinfo-streamdeck#18]
the "type" pull-down does not affect the "title" in any way

I am unable to modify it*
I definitely need to because I am keeping careful control of brightness on my unit
everything has to be scaled and match with all the "levels" of everything else

the default font and brightness is messing with "my clock"
cant keep them separated in my mind

**Comment by shayne** [comment]
Added support to change Title / Value text. It's rendered separate from the default Stream Deck label. There's a new slider for each value.

https://github.com/shayne/hwinfo-streamdeck/releases/tag/v1.1.2

**Comment by shayne** [comment]
Changing the title color should work, check the 1.1.2 update to change the size of the title.
