### ISSUE TITLE
how to change the text

### ISSUE THREAD

**Issue by thebonden** [shayne/hwinfo-streamdeck#19]
95/5000
hi how do you convert Download speed to MB / s instead of KB / s so that both text and numbers fit

how to show Mbps 
what should I divide it by

**Comment by shayne** [comment]
If you divide kilobytes by 125, the result is megabits.
![image](https://user-images.githubusercontent.com/79330/87992957-38836480-ca9e-11ea-8488-54e9fab1a413.png)
![image](https://user-images.githubusercontent.com/79330/87992969-40430900-ca9e-11ea-8d5c-8b53cd277d87.png)
