### ISSUE TITLE
The letter 'n' in title is read as the function '/n'.

### ISSUE THREAD

**Issue by Volante98** [shayne/hwinfo-streamdeck#21]
The word 'Intel' is whown as:
'I
tel'

**Comment by BarRaider** [comment]
I don't think this plugin is actively maintained anymore 😕

**Comment by shayne** [comment]
I've recently rewritten the whole thing to support features like different backends and remote support.

It will also allow me to open-source the plugin side of things, the hardware service that talks to HWiNFO will have to remain closed source per my agreement with them, however.

**Comment by shayne** [comment]
> The word 'Intel' is whown as:
> 'I
> tel'

Can you show me a screenshot?

**Comment by BarRaider** [comment]
@shayne thanks for your update, that's good news. I was planning on creating a similar plugin given it seemed this was no longer maintained. Feel free to reach out if you would like to collaborate. http://discord.barraider.com

**Comment by xoaaC** [comment]
![StreamDeck_HAC4ueSyMn](https://user-images.githubusercontent.com/35452459/93721603-abd64f00-fb91-11ea-94fb-097d36e48f45.png)

I attached a picture of the problem @Volante98 mentioned as you requested.

**Comment by shayne** [comment]
v2.0.0 has support for "\n" or newlines (shift+enter) entered in title
