### ISSUE TITLE
Not fully connected to HWINFO64

### ISSUE THREAD

**Issue by willie68** [shayne/hwinfo-streamdeck#22]
I just installed the actual versions of HWINFO64 (tested with 6.30 and 6.31-BETA) But i can't get this working. 
All sensors will be readed out of the HWINFO, but the actual value will not be readed.
What did i wrong?
![Screenshot 2020-09-15 14 39 11](https://user-images.githubusercontent.com/5518382/93211623-cb204700-f761-11ea-89ce-f09a0240b6db.png)
![Screenshot 2020-09-15 14 39 57](https://user-images.githubusercontent.com/5518382/93211631-cd82a100-f761-11ea-903f-26ed2fab5383.png)
![Screenshot 2020-09-15 14 39 44](https://user-images.githubusercontent.com/5518382/93211638-cf4c6480-f761-11ea-9b6b-2531bf3d3213.png)

**Comment by detlefs** [comment]
Hi,

I found the same issue using HWInfo 6.31.4260
Is there a way we can help diagnosing this? Like, is there any log file we may provide?

**Comment by detlefs** [comment]
@willie68 ,
please try enabling Persistent Driver on the Driver Management settings tab. It worked for me after enabling it.
Though, I'm not sure if the setting really matters...
 I'm using HWiNFO64 6.32-4270...

**Comment by willie68** [comment]
Sorry, but no change. 
The plugin reads the sensors (I think they are comming from HWINfo64 process) and if i select sensor and reading, i get that message. In principle, communication with the program works, but the sensor values can still not be read out.

**Comment by Alex6511** [comment]
Hey, I had this problem. Installing via the installer version seems to have fixed it. Unfortunetly the beta version isn't available as an installer, so working out how to support portable would be nice.

**Comment by willie68** [comment]
Installing seems to work... so this issue is about the Portable Version.

**Comment by shayne** [comment]
Check v2.0.0 will test against portable version
