### ISSUE TITLE
Sometimes hangs/stops updating tiles

### ISSUE THREAD

**Issue by dgw** [shayne/hwinfo-streamdeck#23]
I've noticed that sometimes, my HWiNFO64 tiles stop updating. Usually I notice this when unlocking the system (Win10 x64 1909).

However, the fix seems fairly simple. Normally, opening my Task Manager and killing the `hwinfo.exe` process of this plugin forces it to respawn and makes my HWiNFO64 tiles work again.

Not sure yet if it's a "real" bug, or a quirk of how my system is set up. My StreamDeck is disabled/enabled by Windows tasks when the workstation locks/unlocks (to let me keep "Sleep: Never" but still turn off the unit when my PC is not in use). Not sure if losing communication to the unit directly or indirectly affects this plugin.

Are there logs anywhere that might give a hint at what's happening? Happy to help debug in any way I can, if this seems like it might be worth trying to fix in a future update.

**Comment by shayne** [comment]
v2.0.0 has major refactor/changes... please test and reopen if continues
