### ISSUE TITLE
Incompatibility with new version 7

### ISSUE THREAD

**Issue by jplanglais** [shayne/hwinfo-streamdeck#27]
Just installed HWInfo64 version 7 and lost all integration

**Comment by grimsi** [comment]
They changed their pricing model starting with version 7.0

Now the free version only supports up to 12h of shared memory access, after that you need to manually enable it again.
So if you want to use HWInfo with this plugin, do not update (or install the older version if you already updated).

**Comment by jplanglais** [comment]
> 
> 
> They changed their pricing model starting with version 7.0
> 
> Now the free version only supports up to 12h of shared memory access, after that you need to manually enable it again.
> So if you want to use HWInfo with this plugin, do not update (or install the older version if you already updated).

I noticed and tried re-activating the Shared Memory option but it still wouldn't show any sensor. I eventually went back to 6.42 and confirm it works.

**Comment by grimsi** [comment]
Did you install it via installer or did you use the portable version? I heard the portable version does not work because of the driver used by HWInfo

**Comment by jplanglais** [comment]
> 
> Did you install it via installer or did you use the portable version? I heard the portable version does not work because of the driver used by HWInfo

Via installer (Full version)

**Comment by drksilenc** [comment]
So i have the 7.0 pro version do you know how to enable shared memory access in it?

**Comment by rehanhooda** [comment]
> So i have the 7.0 pro version do you know how to enable shared memory access in it?

Launch the program. Find its icon in the taskbar, right-click and then click on "Settings". You will find "Shared Memory Support" in the first "General/User Interface" tab. Enable that, leave rest of the settings as is, should work.

**Comment by alvoram** [comment]
Definitely works with with ver. 7 once you enable 'Shared Memory Support' again. 

So if we buy the 'pro' version of hwinfo, we will not have to keep enabling that option, but with the free version we will have to manually enable shared memory support every 12 hours.

**Comment by sammer2001** [comment]
I just updated to v7 and bought a licence and the addon doesn't seem to be working.

**Comment by jplanglais** [comment]
Did you re-enable shared memory access?


________________________________

**Comment by sammer2001** [comment]
I forgot to but I just did and it's working now.

**Comment by dgw** [comment]
I will reinstall the last 6.xx version of HWiNFO to keep this plugin working, because it's the _only_ reason I ever installed HWiNFO in the first place. But long-term, what are the chances that this plugin can be rewritten so it won't require SHM?

**Comment by Carbonicdk** [comment]
Can this fix for Rainmeter work for this plugin too?
https://forum.rainmeter.net/viewtopic.php?f=127&t=37160

**Comment by DeanAmiridis** [comment]
Can confirm after purchasing pro and re-enabling Shared Memory Access it works.

Please note, if you go this route: Restart HWInfo64 & StreamDeck software.

**Comment by drksilenc** [comment]
Worked for me.

**Comment by Carbonicdk** [comment]
Spending 20USD a year to have a free plugin show data from an application that is otherwise free for private use is not a viable solution. A way to get the info without a pro license like Rainmeter managed should be possible.

**Comment by greghesp** [comment]
Anyone got a link to the last v6 beta?  Seems they've removed it all from their site

**Comment by DeanAmiridis** [comment]
> 
> 
> Spending 20USD a year to have a free plugin show data from an application that is otherwise free for private use is not a viable solution. A way to get the info without a pro license like Rainmeter managed should be possible.

Agreed -- but considering I rely on my streamdeck having this information up, it is what it is. Until a free solution surfaces, this is the "fix".

**Comment by synth3tk** [comment]
The README should probably be updated to mention the workarounds listed here.

**Comment by Fredoias** [comment]
I uninstalled v7 and downloaded v6.42 and have had no issues since. This where I found it. https://www.fosshub.com/HWiNFO-old.html
