### ISSUE TITLE
temperature is displayed as □□C.

### ISSUE THREAD

**Issue by ma3ru3** [shayne/hwinfo-streamdeck#29]
I am using hwinfo-Streamdeck v1.2.0 and HWiNFO64 7.02 in Windows 10 Japanese environment.
But only the temperature display is wrong. For example, the temperature is displayed as □□C.
Probably a font problem. Is there any way to fix it?

![image](https://user-images.githubusercontent.com/83626415/116959790-b0dbaf00-acd9-11eb-8614-a65a9425fd99.png)

**Comment by luvisra** [comment]
same issue.

**Comment by ma3ru3** [comment]
Thanks! It's fixed!

![image](https://user-images.githubusercontent.com/83626415/117452503-cc1b1880-af7e-11eb-8b8d-1e24185d2cf6.png)

**Comment by luvisra** [comment]
Perpect!
