### ISSUE TITLE
Upgraded to HWiNFO pro SD stopped detecting

### ISSUE THREAD

**Issue by percusswords** [shayne/hwinfo-streamdeck#30]
Hiya,
I love this utility, but as soon as I upgraded to HWiNFO pro, my stream deck stayed stuck on the "Please Launch HWiNFO64" icon. None of my settings have changed from before when it was working fine. Does the plugin need to be updated, or is there an additional settings I need to tweak now that it's the pro version?
Thanks in advance!

**Comment by MalakieUSN** [comment]
Having same identical problem.. just upgraded to the pro version and now Stream deck stays stuck on "Please launch....."

**Comment by shayne** [comment]
Fixed in v2.0.0

**Comment by MalakieUSN** [comment]
> Fixed in v2.0.0

Awesome and thanks!  I reply on your program now!
