### ISSUE TITLE
HWInfo64 v7.06-4500 breaks plugin

### ISSUE THREAD

**Issue by Valethar** [shayne/hwinfo-streamdeck#31]
The update to HWInfo64 that rolled out today appears to be not playing nice with the plugin.

Completely uninstalled the plugin, restarted the PC, reinstalled the plugin (2.0.0), double checked all of the settings, but still get an error stating the plugin cannot communicate with HWINfo64.

![HWInfo64_001](https://user-images.githubusercontent.com/33778407/124702521-501d4e00-dea5-11eb-9633-4d42f243e9ec.png)

**Comment by Unfaced85** [comment]
I can confirm this - just updated hwinfo to this Version and the Plugin stopped showing hwinfo on the Streamdeck

**Comment by revlisoft** [comment]
I can also confirm this that it stopped working as well.  I have the pro version as well so there is no 12 hour limitation on shared memory support.

**Comment by rehsd** [comment]
Same issue here. I have HWiNFO Pro. I had Plugin 1.2.0 and installed 2.0.0 to resolve the issue (I did not uninstall 1.2.0).

**Comment by shayne** [comment]
HWiNFO changed the executable name...

If you don't want to upgrade here's a manual fix:

Open `%appdata%\Elgato\StreamDeck\Plugins\com.exension.hwinfo.sdPlugin\manifest.json`

Change:
```json
  "ApplicationsToMonitor": {
    "windows": "HWiNFO64.EXE",
  },
```

To:
```json
  "ApplicationsToMonitor": {
    "windows": ["HWiNFO64.EXE", "HWiNFO64.exe"]
  },
```

Restart StreamDeck software.

**Comment by revlisoft** [comment]
Thanks for the quick workaround! Worked like a charm!
