### ISSUE TITLE
HWInfo64 Free limitation 12h

### ISSUE THREAD

**Issue by syrm** [shayne/hwinfo-streamdeck#32]
Hello,

HWInfo64 Free edition now have a limitation : 
```
HWiNFO64 (non-Pro) has a time-limited Shared Memory support to 12 hours. When this limit is reached during run-time, this feature will be automatically deactivated (and requires manual enabling again)
```

Could you consider using Open Hardware Monitor instead ?
https://openhardwaremonitor.org/
http://openhardwaremonitor.org/wordpress/wp-content/uploads/2011/04/OpenHardwareMonitor-WMI.pdf

**Comment by shayne** [comment]
v2.0.0 refactor has abstracted hwinfo away from the core plugin making it possible to write integrations with other providers like OpenHardwareMonitor or AIDA64... 

Keep an eye out for that.
