### ISSUE TITLE
HWinfo 7.06 doesn't display on StreamDeck icon

### ISSUE THREAD

**Issue by chadmccan** [shayne/hwinfo-streamdeck#34]
After updating to HWinfo 7.06, my streamdeck integrations all display "Please Launch HWINFO64". It's obviously running. And I have a licensed version with shared memory support enabled. I also can see the sensors in the streamdeck button, it's just not displaying on the button.

Any advice?

**Comment by brettonlewis** [comment]
Having the same issue.

**Comment by btcdtc** [comment]
have you guys tried to update to pre-release 2.0.0? it should help.

**Comment by christopherjtaylor** [comment]
Thanks for the tip @btcdtc - updating to 2.0.0 fixed the issue for me.

**Comment by brettonlewis** [comment]
Same with me! Didn't see the pre-release. Thanks @btcdtc
