### ISSUE TITLE
2.0.0 plug in stops running....

### ISSUE THREAD

**Issue by MalakieUSN** [shayne/hwinfo-streamdeck#36]
Been using the latest plugin since you updated it...  But after a few days of the same issue, it is having a problem..

Basically sometimes it will not load the HWINFO specs on the first load/run.  You have to exit streamdeck completely and start it again.   Also, after a period of time (have not yet isolated exactly how long yet), it just stops working.  It stops updating and you again have to exit streamdeck and load it again..

NOTE, I have TWO streamdecks running and I am thinking that could be possibly part of the problem?  I.E. it is not updating the 2nd or higher hardware box after a while.. almost like it goes to sleep...  The reason I say this is my first streamdeck (used for other stuff) does NOT stop working.. Only the one HWINFO is used on stops.

**Comment by goofy-somebody** [comment]
For me the plugin stops working after the following:

Reboot
Restart Stream Deck
Restart HWINFO

I don't think I've seen it stop registering yet though.

The attached log file reflects the following procedure:

Start HWINFO and wait for it to load
Start Stream Deck
Quit HWINFO
Quit Stream Deck

Starting HWINFO or Stream Deck doesn't matter in the order, still produces the same log
[hwinfo.log](https://github.com/shayne/hwinfo-streamdeck/files/6796307/hwinfo.log)

**Comment by goofy-somebody** [comment]
Just noticed that there is a 2.0.1 release, try that and see if it fixes this issue.
