### ISSUE TITLE
Implement HWiNFO Gadget method support

### ISSUE THREAD

**Issue by MMilesMM** [shayne/hwinfo-streamdeck#38]
Shared memory is now limited to a 12 hour period. After that you have to manually reenable it. This limitation can be remove by buying the new pro version. But they state, that they opened up the interface to read all the values. So there might be a chance to circumvent it?

**Comment by Tunakirkoc** [comment]
Juste use the older version 6.42 here [https://www.fosshub.com/HWiNFO-old.html](url)

**Comment by leeloo-1337** [comment]
The plugin no longer works with a Pro license even. Just always says Please Launch HWiNFO64 despite it clearly reporting the data: 
![image](https://user-images.githubusercontent.com/67878195/127022021-fdf0ad97-776b-4f5a-ab58-1084f6236e41.png)

**Comment by miniman13** [comment]
The setting is not in the Sensors setting page, its on the settings page that you hit when you first open the App.

**Comment by pannal** [comment]
There's actually an easy way to properly use the newer HWiNFO versions with 3rd party access without paying for it. Officially.

https://docs.rainmeter.net/tips/hwinfo/

The plugin author just needs to implement it.

**Comment by shayne** [comment]
I built this using the shared memory support and understand that HWiNFO has changed their business model and the functionality of shared memory is now time limited. I don't plan on implementing the gadget method as recommended by Rainmeter. I'd suggest supporting HWiNFO if you find yourself hitting the time limit.

**Comment by pannal** [comment]
> I built this using the shared memory support and understand that HWiNFO has changed their business model and the functionality of shared memory is now time limited. I don't plan on implementing the gadget method as recommended by Rainmeter. I'd suggest supporting HWiNFO if you find yourself hitting the time limit.

Well, HWiNFO implemented the time limit so that commercial use cases have to pay. The "gadget" method is officially meant for non-commercial use and doesn't even need a shared memory approach.

It isn't like the gadget method is something unofficial or discouraged.
