### ISSUE TITLE
Cannot add new sensors after latest updates

### ISSUE THREAD

**Issue by szalkerous** [shayne/hwinfo-streamdeck#43]
After the latest updates of the plugin and HWiNFO the sensor dropdown is unable to load, even though the existing sensors continue to read data.

Trying to re-launch both applications does not fix the issue. Launching both apps as admin does not fix.

Un and Re-installing plugin does not fix the issue.

Double checking all HWiNFO settings I do not see any that are out of place.

![Screenshot 2021-09-13 164651](https://user-images.githubusercontent.com/8646173/133154542-b9ea3d57-2622-43a8-a45b-0f022e085f1e.png)

![Screenshot 2021-09-13 165010](https://user-images.githubusercontent.com/8646173/133154562-a0f06ac2-f205-4c33-a3c2-0a4f87456e8e.png)

**Comment by szalkerous** [comment]
Plugin ver 2.1.0
HWiNFO64 ver 7.10-4540

**Comment by jlglvz** [comment]
same problem...

**Comment by shayne** [comment]
I'm able to reproduce on my end. Will take a look later today when I have some time.

**Comment by shayne** [comment]
Fixed in v2.0.2

https://github.com/shayne/hwinfo-streamdeck/releases/tag/v2.0.2
