### ISSUE TITLE
"Dual" titles?

### ISSUE THREAD

**Issue by madvillainwill** [shayne/hwinfo-streamdeck#56]
LOVE the plugin. Excellent support. This has removed my need for a cumbersome secondary display.

Small issue - when adding a title and attempting to customize it, there appears to be a bug where it duplicates the name. You can modify and move the "second title" like normal, but the "first" title is stuck where it is and is not editable. When trying to delete this field, it removes "both" title entries. Is this a known issue or am I doing something silly? Tried to google it but.. no luck.
![aa](https://user-images.githubusercontent.com/104272076/164917095-1801d407-b2d2-4d32-a3ce-23a523f9853f.png)

**Comment by digitaldynamo83** [comment]
I didn't have this issue until updating to v6 of the Stream Deck software.

In the font options window you have up, uncheck "Show Title". This will hide the text the Stream Deck software is overlaying, so only the plug-in's text will appear.

**Comment by dtomcat** [comment]
I also have this... the streamdeck title is so much more clear than HWinfo madatory title.  Is this anyway to stop plugin from always displaying a title?

**Comment by dtomcat** [comment]
maybe lower the min title size to 0?

**Comment by shayne** [comment]
When I wrote the plugin, the title support with the Streamdeck could have been better.

To remove the duplicate title, uncheck the box "Show Title".

If you want no title to display, you can remove the title text in the Title text box.

**Comment by dtomcat** [comment]
The title is clearer with stream deck … I’d like to hide the title from the plug-in.

**Comment by dtomcat** [comment]
I was able to do a work around.   I changed the HTML code to allow range 0 - 20.  With that change, you can select 0.5 font size (0.0 kicks it back to 10.5).  I may work with it later to allow zero... but 0.5 is basically non-existent.  This will allow you to remove the title from the plug-in and use stream decks title function.  probably just a font issue, but this allows the title to be clear and neat.  (not taking away from the work Shayne did... this is great work, just a tweak to make a bit better on the eyes)
