### ISSUE TITLE
request for feature

### ISSUE THREAD

**Issue by ravage007** [shayne/hwinfo-streamdeck#6]
is there a way we can get the button to act like a button or the display like what I would love to do is see the load of my CPU tap that button and take me to a profile with what's the load on every cor or some think like that  basically I'm asking for a feature where if you tap the button it could switch to another profile where I could have the information like that

**Comment by exension** [comment]
Interesting... just to make sure we're on the same page can you sketch it out? ASCII art or mspaint.

**Comment by ravage007** [comment]
sorry I'm not a good artist things like that but I did make this little video that might be able to help you 
https://youtu.be/dXBPflDWz8M

**Comment by exension** [comment]
Super helpful. I'll be implementing something along these lines. Thanks!

**Comment by ravage007** [comment]
I can't wait and I hope it's soon this is one of the most helpful mods for this stream deck that I found

**Comment by shayne** [comment]
This is on hold until the Stream Deck SDK supports the ability to change layouts via SDK
