### ISSUE TITLE
v2.0.5 won't install

### ISSUE THREAD

**Issue by RBMDragon** [shayne/hwinfo-streamdeck#73]
Newest version won't install on Stream Deck.

**Comment by robinrm** [comment]
same issue. If already installed it would breack the installation. After reinstalling it says "installed" but doesn't work. After restarting Stream Deck it isn't installed anymore.

**Comment by RBMDragon** [comment]
Okay; manually removing the plugin in the %appdata% folder solved the issue.
Tested with both the earlier version and the newer one.

If someone else has this issue, make sure to remove the previous version first.

**Comment by robinrm** [comment]
True.

Delete the folder `AppData\Roaming\Elgato\StreamDeck\Plugins\com.exension.hwinfo.sdPlugin` and install it again from the plugin store. Working fine after that!
