### ISSUE TITLE
Loading senor list... Win 10 + 6.00 / 6.10 Installer

### ISSUE THREAD

**Issue by molekm** [shayne/hwinfo-streamdeck#8]
![image](https://user-images.githubusercontent.com/52691210/64096161-cc4e2400-cd58-11e9-82cd-5294edf5d053.png)

Keeps loading sensor list.

HWinfo set to shared memory support.

Tried 6.00 / 6.10 (installer, 64)

Newest Stream Deck +plugin

**Comment by LesterCovax** [comment]
Have to ask, but you've confirmed that you clicked to run the sensors, and it is actually running?  Here are my settings for comparison FWIW:

![image](https://user-images.githubusercontent.com/34850610/64196392-c38d4900-ce51-11e9-9a7d-a6a2f81f8856.png)

**Comment by shayne** [comment]
Make sure you're running the installed version, not portable.
