### ISSUE TITLE
Show VCore as Float Value not Int?

### ISSUE THREAD

**Issue by ralleh** [shayne/hwinfo-streamdeck#82]
Hey,

I wanna display the VCore Reading on my Stream Deck via ur plugin, but somehow I cannot get the right settings for the actual VCore to be displayed (always showing an Int, not the Float):

![image](https://github.com/shayne/hwinfo-streamdeck/assets/13209271/cc829dbd-47d0-444e-82b0-d83cf6350a1b)

Is there a way to get the real VCore Reading (1.421V instead of just 1V)?

Thanks a lot in advance, also for your great work with this plugin!

Kind regards,
Ralf

**Comment by shayne** [comment]
In Advanced if you change the format to `%f` does it show the proper float value?

**Comment by ralleh** [comment]
> In Advanced if you change the format to `%f` does it show the proper float value?

Thanks a lot, that worked!

It shows the full VCore value (as in 1,34093) now, though. Is there a syntax/way to cut it after the first 2 digits, to get the "normal" 1,34V reading, by any chance?

**Comment by shayne** [comment]
`%.2f` should do it

**Comment by ralleh** [comment]
Thanks a lot, really appreciated!
