### ISSUE TITLE
[Feature Request] Change text size + Open-source the code

### ISSUE THREAD

**Issue by LesterCovax** [shayne/hwinfo-streamdeck#9]
I'm kind of blind it seems and can't read the value text well (even though it's not completely necessary with the graph background).  The ability to change the font/size would be great, as `fmt` doesn't have that capability AFAIK.

Also, do you plan to open-source the code?  I'd be willing to help with some of these fixes if you did so.  Would also make me feel more comfortable running it.  Cheers.

**Comment by shayne** [comment]
Added support to change Title / Value text. It's rendered separate from the default Stream Deck label. There's a new slider for each value.

https://github.com/shayne/hwinfo-streamdeck/releases/tag/v1.1.2


Unfortunately unable to open-source the HWiNFO code per the author's request. I would if I could! It's simply an issue that the memory API is to be kept hidden. I may look at separating the code into a separate binary and having it talk to the StreamDeck plugin.
